adj1 = input("Enter an adjective: ")
adj2 = input("Enter an another adjective: ")
adj3 = input("Enter an another adjective: ")
adj4 = input("Enter an another adjective: ")
nationality = input("Enter a nationality: ")
name = input("Enter a name: ")
noun1 = input("Enter a another noun: ")
noun2 = input("Enter a another noun: ")
noun3 = input("Enter a another noun: ")
pluralnoun = input("Enter a noun in plural: ")
number = input("Enter a number: ")
number = input ("Enter another number: ")
shape = input("Enter a shape in plural: ")
food1 = input("Enter a food: ")
food2 = input("Enter a another food: ")

print("Pizza was invented by a "+adj1+chef named . To make a piza, you need to take a lump of ")
